version: "3.8"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8081
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    ports:
      - 8081:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
networks:
  dockge_default:
    external: true
